name: First Workflow
# Evento que dispara o workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        # comando que ser√° executado na linha de comando
        run: echo "Hello, world!"
      - name: Print goodbye
        run: echo "Done. Bye!"
